{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let site_url=ezini('SiteSettings','SiteURL')}
{set-block scope=root variable=subject}{'%1 registration info'|i18n('design/wiki/user/register',,array($site_url))}{/set-block}
{'Thank you for registering at %siteurl.'|i18n('design/wiki/user/register',,hash('%siteurl',$site_url))}

{'Your account information'|i18n('design/wiki/user/register')}
{'Username'|i18n('design/wiki/user/register')}: {$user.login}
{'Email'|i18n('design/wiki/user/register')}: {$user.email}

{section show=$password}
{'Password'|i18n('design/wiki/user/register')}: {$password}
{/section}


{section show=and( is_set( $hash ), $hash )}

{'Click the following URL to confirm your account'|i18n('design/wiki/user/register')}
http://{$site_url}/user/activate/{$hash}/{$object.main_node_id}

{/section}


{'Link to user information'|i18n('design/wiki/user/register')}:
http://{$site_url}/content/view/full/{$object.main_node_id}

{/let}
